from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:  # pragma: no cover
        return str(self.value)


class Environment(StrEnum):
    DEMO = "DEMO"
    LIVE = "LIVE"


class Role(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    READ_ONLY = "READ_ONLY"


class AccountStatus(StrEnum):
    DISCONNECTED = "DISCONNECTED"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    AUTH_FAILED = "AUTH_FAILED"
    ERROR = "ERROR"


class BotStatus(StrEnum):
    CREATED = "CREATED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    ERROR = "ERROR"
    CRASHED = "CRASHED"
    RESTARTING = "RESTARTING"
    LOCKED = "LOCKED"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUBMITTED = "SUBMITTED"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"
    FAILED = "FAILED"


ACTIVE_ORDER_STATUSES = (
    OrderStatus.PENDING, OrderStatus.PROCESSING, OrderStatus.SUBMITTED,
    OrderStatus.ACCEPTED, OrderStatus.PARTIALLY_FILLED,
)
TERMINAL_ORDER_STATUSES = (
    OrderStatus.FILLED, OrderStatus.REJECTED, OrderStatus.CANCELLED, OrderStatus.FAILED,
)


class Side(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class StrategyVersionStatus(StrEnum):
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class LockScope(StrEnum):
    GLOBAL = "GLOBAL"
    ACCOUNT = "ACCOUNT"
    BOT = "BOT"
    STRATEGY = "STRATEGY"


class Severity(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    NOTICE = "NOTICE"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class Category(StrEnum):
    SYSTEM = "SYSTEM"
    AUTH = "AUTH"
    CTRADER = "CTRADER"
    CONNECTION = "CONNECTION"
    HEARTBEAT = "HEARTBEAT"
    BOT = "BOT"
    STRATEGY = "STRATEGY"
    SIGNAL = "SIGNAL"
    RISK = "RISK"
    ORDER = "ORDER"
    POSITION = "POSITION"
    RECONCILIATION = "RECONCILIATION"
    DATABASE = "DATABASE"
    TELEGRAM = "TELEGRAM"
    ERROR = "ERROR"
    SECURITY = "SECURITY"
    WATCHDOG = "WATCHDOG"
    NOTIFICATION = "NOTIFICATION"


class MarketDataStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    NO_DATA = "NO_DATA"


class RiskReason(StrEnum):
    APPROVED = "APPROVED"
    TRADING_DISABLED = "RISK_REJECTED_TRADING_DISABLED"
    LIVE_DISABLED = "RISK_REJECTED_LIVE_DISABLED"
    LOCKED = "RISK_REJECTED_LOCKED"
    NOT_CONNECTED = "RISK_REJECTED_NOT_CONNECTED"
    PERMISSION = "RISK_REJECTED_TRADING_PERMISSION"
    SYMBOL_NOT_ALLOWED = "RISK_REJECTED_SYMBOL_NOT_ALLOWED"
    SESSION = "RISK_REJECTED_SESSION"
    STALE_DATA = "RISK_REJECTED_STALE_DATA"
    SPREAD = "RISK_REJECTED_SPREAD"
    MAX_TRADES_DAY = "RISK_REJECTED_MAX_TRADES_PER_DAY"
    MAX_OPEN_POSITIONS = "RISK_REJECTED_MAX_OPEN_POSITIONS"
    DAILY_LOSS = "RISK_REJECTED_DAILY_LOSS"
    DRAWDOWN = "RISK_REJECTED_DRAWDOWN"
    CONSECUTIVE_LOSSES = "RISK_REJECTED_CONSECUTIVE_LOSSES"
    NO_STOP_LOSS = "RISK_REJECTED_NO_STOP_LOSS"
    NO_CONVERSION = "RISK_REJECTED_NO_CONVERSION_RATE"
    MIN_VOLUME = "RISK_REJECTED_MIN_VOLUME"
    MAX_EXPOSURE = "RISK_REJECTED_MAX_EXPOSURE"
    SYMBOL_EXPOSURE = "RISK_REJECTED_SYMBOL_EXPOSURE"
    ACCOUNT_EXPOSURE = "RISK_REJECTED_ACCOUNT_EXPOSURE"
    FREE_MARGIN = "RISK_REJECTED_FREE_MARGIN"
    INVALID_SIGNAL = "RISK_REJECTED_INVALID_SIGNAL"
    NO_ACCOUNT_DATA = "RISK_REJECTED_NO_ACCOUNT_DATA"
